name: "Bug report"
description: "Found something that's not working as expected? Provide detailed information about the issue to help get it resolved."
labels:
  - bug

body:
  - id: description
    type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the bug"
      description: "Tell what went wrong and how it's affecting your work."

  - id: what-you-see
    type: textarea
    attributes:
      label: "What do you see?"
      description: "Share what's actually happening - error messages, unexpected behavior, or missing functionality. Screenshots are welcome!"

  - id: what-you-expect
    type: textarea
    attributes:
      label: "What do you expect to see?"
      description: "Describe the intended behavior - what should have happened instead?"

  - id: steps-to-reproduce
    type: textarea
    validations:
      required: false
    attributes:
      label: "List the steps that must be taken to reproduce this issue"
      description: "Provide exact steps to recreate this bug. Include any code snippets, configuration files, or commands used. The easier it is to reproduce, the quicker it can be fixed!"
      placeholder: |
        1. Start the application
        2. Navigate to localhost:8080/metrics
        3. No metrics are displayed

  - id: version
    type: input
    attributes:
      label: "Version"
      description: "Which version of the project are you using? (check package.json, tags, or release notes if unsure)"

  - id: additional-information
    type: textarea
    attributes:
      label: "Additional information"
      description: "Anything else that might help solve this? Environment details, related issues, or workarounds you've tried."
