name: Build tagged image

on:
  push:
    tags:
      - "v*.*.*" # e.g., "v1.2.32"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set ENV variables
        run: |
          echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set TAG
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER}/${REPO_NAME}/${REPO_NAME}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Tag Name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Validate Tag Format
        run: |
          if [[ ! "$TAG_NAME" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            echo "Invalid tag format: $TAG_NAME. Expected format: v<major>.<minor>.<patch> (e.g., v1.2.32)"
            exit 1
          fi

      - name: Derive Additional Tags
        id: derive_tags
        run: |
          # Remove the 'v' prefix
          VERSION=${TAG_NAME#v}

          # Extract major, minor, and patch
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          # Define the tags
          TAG_V1="v$MAJOR"
          TAG_V1_2="v$MAJOR.$MINOR"
          TAG_FULL="v$MAJOR.$MINOR.$PATCH"

          # Export the tags as environment variables
          echo "TAG_V1=$TAG_V1" >> $GITHUB_ENV
          echo "TAG_V1_2=$TAG_V1_2" >> $GITHUB_ENV
          echo "TAG_FULL=$TAG_FULL" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.TAG_V1 }}
            ${{ env.IMAGE_NAME }}:${{ env.TAG_V1_2 }}
            ${{ env.IMAGE_NAME }}:${{ env.TAG_FULL }}
